added tmux

diff --git a/dot_zprofile b/dot_zprofile
--- a/dot_zprofile
+++ b/dot_zprofile
@@ -1,1 +1,14 @@
+if [ -x /opt/homebrew/bin/brew ]; then
+  eval "$(/opt/homebrew/bin/brew shellenv)"
+elif [ -x /usr/local/bin/brew ]; then
+  eval "$(/usr/local/bin/brew shellenv)"
+elif [ -x /home/linuxbrew/.linuxbrew/bin/brew ]; then
+  eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
+else
+  echo "[chezmoi] Homebrew not found. Please install Homebrew first."; exit 1
+fi
+
+# Basic PATH
+export PATH="$HOME/.local/bin:$PATH"
+
 eval "$(mise activate zsh --shims)"
